var trStrings = {
	postErrors : {
		contacts : "Error retrieving contacts data: ",
		saveContacts : "Error saving contacts data: ",
		cycles : "Error retrieving cycles: ",
		cycleData : "Error retrieving cycle data: ",
		status : "Error retrieving current status: ",
		testResults : "Error retrieving results of network test: ",
		logoUpload : "Error sending logo to device: ",
		restore : "Error sending settings file to device: ",
		defaults : "Error restoring settings to default: ",
		setup : "Error retrieving setup data: ",
		lan : "Error sending lan settings to device: ",
		remotes : "Error sending remote settings to device: ",
		notif : "Error sending notification settings to device: ",
		time : "Error sending time settings to device: ",
		password : "Error sending password settings to device: ",
		updates : "Error sending update settings to device: ",
		testRemote : "Email settings could not be confirmed: ",
		updateTime : "Failed to send request to update time: ",
		updateFirmware : "Failed to send interface update to server: ",
		email : "Error sending email request to server: ",
	    remote: "Error retrieving screen image: ",
	    repair: "The service log is currently empty.<br/>A new entry can be added using the New entry section below.<br/>",
	    addNewRepair: "Failed to add new repair record: ",
	    remoteAccess: "Failed to initiate remote access: "		
	},
	dataErrors : {
		contacts : "Failed to save contacts.",
		cycleData : "Failed to obtain cycle data.",
		logoUpload : "Failed to upload logo.",
		testResults : "Failed to get network test results.",
		restore : "Failed to upload settings.",
		defaults : "Failed to restore settings to defaults.",
		lan : "Failed to save lan settings.",
		remote : "Failed to save remote settings.",
		notif : "Failed to save notification settings.",
		time : "Failed to save time settings.",
		password : "Failed to save password settings.",
		updates : "Failed to save update settings.",
		testRemote : "Email settings could not be confirmed. Please verify your settings.",
		updateTime : "Failed to update time.",
		updateFirmware : "Failed to update interface.",
		email : "Failed to send email.",
        unitEnumeration: "Error retrieving list of devices: ",
        addNewRepair: "Failed to add new repair record."		
	},
	success : {
		contacts : "Contact settings saved.",
		restore : "Settings successfully uploaded.",
		defaults : "Settings have been restored to defaults.",
		lan : "Lan settings saved.",
		remote : "Remote settings saved.",
		notif : "Notification settings saved.",
		time : "Time settings saved.",
		password : "Password settings saved.",
		updates : "Update settings saved.",
		testRemote : "Email settings have been confirmed. Please check your inbox for the test email.",
		updateTime : "Time updated.",
		updateFirmware : "null",
		email : "Email sent.",
		addNewRepair: "Added new repair record.",
		enableAccess:"Enable",
		disableAccess:"Disable"
	},
	confirm : {
		defaults : "Are you sure you want to reset all settings back to the defaults?"
	},
	alerts : {
		password : "Entered passwords do not match."
	}
};

var injectStrings = {
	Token : "Token: ",
	tipContactsPrivacy : "Please agree to the Terms of Use and Privacy Policy to enable Email Notifications.",
	tipTimeAutoTimeDisabled : "Manual time setup detected.<br/><br/>Auto time update will now be disabled.<br/><br/>To re-enable auto time update, check this option and press Save.",
	tipTestPrivacy : "Please agree to the Terms of Use and Privacy Policy on the <a class=\"tipLinkContacts\">Contacts</a> page.",
	tipTestNotifications : "Please check All or CF for at least one recipient on the <a class=\"tipLinkNotifications\">Notifications</a> page.",
	tipTestRemoteLocal : "One or more fields missing above, please complete before Test.",
	tipTestNotificationsLocal : "Please check All or CF for at least one recipient above.",
	tipTestRemote : "One or more fields is missing in the <a class=\"tipLinkRemote\">Remote</a> page. Please complete before Test.",
	dialogSaveRemindSave : "Save",
	dialogSaveRemindDiscard : "Discard",
	dialogSaveRemindNotSaved : "Save your changes before proceeding?",
	dialogSaveRemindNote : "NOTE",
	tipBackupSettingsRemote : "Tip: Passwords from the following pages are not saved: <a class=\"tipLinkRemote\">Remote</a> and <a class=\"tipLinkPassword\">Password</a>.",
	tipBackupSettingsNoRemote : "Tip: Password from the following page is not saved: <a class=\"tipLinkPassword\">Password</a>.",
	temperature : "Temperature",
	pressure : "Pressure",
	refreshingList : "Refreshing List. Please wait..."
};
